package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/serdarburakguneri/hobby-streamer/backend/asset-manager/graph/model"
	"github.com/serdarburakguneri/hobby-streamer/backend/asset-manager/internal/asset"
	"github.com/serdarburakguneri/hobby-streamer/backend/pkg/logger"
)

// Assets is the resolver for the assets field.
func (r *bucketResolver) Assets(ctx context.Context, obj *model.Bucket) ([]*model.Asset, error) {
	if obj.AssetIds == nil || len(obj.AssetIds) == 0 {
		return []*model.Asset{}, nil
	}

	assets, err := r.Resolver.AssetService.GetAssetsByIDs(ctx, obj.AssetIds)
	if err != nil {
		return nil, fmt.Errorf("failed to get assets: %w", err)
	}

	var result []*model.Asset
	for _, asset := range assets {
		result = append(result, mapAssetToGraphQL(&asset))
	}

	return result, nil
}

// CreateAsset is the resolver for the createAsset field.
func (r *mutationResolver) CreateAsset(ctx context.Context, input model.AssetInput) (*model.Asset, error) {
	log := logger.Get().WithService("graphql-resolver")

	internalAsset := mapGraphQLAssetInputToAsset(input)

	createdAsset, err := r.Resolver.AssetService.CreateAsset(ctx, internalAsset)
	if err != nil {
		log.WithError(err).Error("Failed to create asset in service")
		return nil, fmt.Errorf("failed to create asset: %w", err)
	}

	return mapAssetToGraphQL(createdAsset), nil
}

// PatchAsset is the resolver for the patchAsset field.
func (r *mutationResolver) PatchAsset(ctx context.Context, id string, patches []*model.JSONPatch) (*model.Asset, error) {
	internalAsset, err := r.Resolver.AssetService.GetAssetByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get asset: %w", err)
	}

	for _, patch := range patches {
		switch patch.Op {
		case "replace":
			switch patch.Path {
			case "/title":
				internalAsset.Title = patch.Value
			case "/description":
				internalAsset.Description = patch.Value

			case "/type":
				if patch.Value != nil {
					// Convert GraphQL enum to internal constant
					switch *patch.Value {
					case "MOVIE":
						assetType := asset.AssetTypeMovie
						internalAsset.Type = &assetType
					case "SERIES":
						assetType := asset.AssetTypeSeries
						internalAsset.Type = &assetType
					case "SEASON":
						assetType := asset.AssetTypeSeason
						internalAsset.Type = &assetType
					case "EPISODE":
						assetType := asset.AssetTypeEpisode
						internalAsset.Type = &assetType
					case "DOCUMENTARY":
						assetType := asset.AssetTypeDocumentary
						internalAsset.Type = &assetType
					case "MUSIC":
						assetType := asset.AssetTypeMusic
						internalAsset.Type = &assetType
					case "PODCAST":
						assetType := asset.AssetTypePodcast
						internalAsset.Type = &assetType
					case "TRAILER":
						assetType := asset.AssetTypeTrailer
						internalAsset.Type = &assetType
					case "BEHIND_THE_SCENES":
						assetType := asset.AssetTypeBehindTheScenes
						internalAsset.Type = &assetType
					case "INTERVIEW":
						assetType := asset.AssetTypeInterview
						internalAsset.Type = &assetType
					default:
						return nil, fmt.Errorf("invalid type value: %s", *patch.Value)
					}
				}
			case "/genre":
				if patch.Value != nil && *patch.Value != "" {
					// Convert GraphQL enum to internal constant
					switch *patch.Value {
					case "ACTION":
						genre := asset.AssetGenreAction
						internalAsset.Genre = &genre
					case "DRAMA":
						genre := asset.AssetGenreDrama
						internalAsset.Genre = &genre
					case "COMEDY":
						genre := asset.AssetGenreComedy
						internalAsset.Genre = &genre
					case "HORROR":
						genre := asset.AssetGenreHorror
						internalAsset.Genre = &genre
					case "SCI_FI":
						genre := asset.AssetGenreSciFi
						internalAsset.Genre = &genre
					case "ROMANCE":
						genre := asset.AssetGenreRomance
						internalAsset.Genre = &genre
					case "THRILLER":
						genre := asset.AssetGenreThriller
						internalAsset.Genre = &genre
					case "FANTASY":
						genre := asset.AssetGenreFantasy
						internalAsset.Genre = &genre
					case "DOCUMENTARY":
						genre := asset.AssetGenreDocumentary
						internalAsset.Genre = &genre
					case "MUSIC":
						genre := asset.AssetGenreMusic
						internalAsset.Genre = &genre
					case "NEWS":
						genre := asset.AssetGenreNews
						internalAsset.Genre = &genre
					case "SPORTS":
						genre := asset.AssetGenreSports
						internalAsset.Genre = &genre
					case "KIDS":
						genre := asset.AssetGenreKids
						internalAsset.Genre = &genre
					case "EDUCATIONAL":
						genre := asset.AssetGenreEducational
						internalAsset.Genre = &genre
					default:
						return nil, fmt.Errorf("invalid genre value: %s", *patch.Value)
					}
				} else {
					internalAsset.Genre = nil
				}
			case "/genres":
				if patch.Value != nil {
					var genres []string
					if err := json.Unmarshal([]byte(*patch.Value), &genres); err != nil {
						return nil, fmt.Errorf("invalid genres format: %w", err)
					}
					internalAsset.Genres = genres
				}
			case "/tags":
				if patch.Value != nil {
					var tags []string
					if err := json.Unmarshal([]byte(*patch.Value), &tags); err != nil {
						return nil, fmt.Errorf("invalid tags format: %w", err)
					}
					internalAsset.Tags = tags
				}
			case "/metadata":
				if patch.Value != nil {
					var metadata map[string]interface{}
					if err := json.Unmarshal([]byte(*patch.Value), &metadata); err != nil {
						return nil, fmt.Errorf("invalid metadata format: %w", err)
					}
					internalAsset.Metadata = metadata
				}
			case "/ownerId":
				internalAsset.OwnerID = patch.Value
			case "/parentId":
				internalAsset.ParentID = patch.Value
			}
		case "remove":
			switch patch.Path {
			case "/title":
				internalAsset.Title = nil
			case "/description":
				internalAsset.Description = nil
			case "/genre":
				internalAsset.Genre = nil
			case "/genres":
				internalAsset.Genres = nil
			case "/tags":
				internalAsset.Tags = nil
			case "/metadata":
				internalAsset.Metadata = nil
			case "/ownerId":
				internalAsset.OwnerID = nil
			case "/parentId":
				internalAsset.ParentID = nil
			}
		}
	}

	err = r.Resolver.AssetService.UpdateAsset(ctx, id, internalAsset)
	if err != nil {
		return nil, fmt.Errorf("failed to patch asset: %w", err)
	}

	updatedAsset, err := r.Resolver.AssetService.GetAssetByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get updated asset: %w", err)
	}

	return mapAssetToGraphQL(updatedAsset), nil
}

// DeleteAsset is the resolver for the deleteAsset field.
func (r *mutationResolver) DeleteAsset(ctx context.Context, id string) (bool, error) {
	err := r.Resolver.AssetService.DeleteAsset(ctx, id)
	if err != nil {
		return false, fmt.Errorf("failed to delete asset: %w", err)
	}
	return true, nil
}

// PatchPublishRule is the resolver for the patchPublishRule field.
func (r *mutationResolver) PatchPublishRule(ctx context.Context, id string, patches []*model.JSONPatch) (*model.Asset, error) {
	internalAsset, err := r.Resolver.AssetService.GetAssetByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get asset: %w", err)
	}

	if internalAsset.PublishRule == nil {
		internalAsset.PublishRule = &asset.PublishRule{}
	}

	for _, patch := range patches {
		switch patch.Op {
		case "replace":
			switch patch.Path {
			case "/publishAt":
				if patch.Value == nil || *patch.Value == "" {
					internalAsset.PublishRule.PublishAt = time.Time{}
				} else {
					publishAt, err := time.Parse(time.RFC3339, *patch.Value)
					if err != nil {
						return nil, fmt.Errorf("invalid publishAt format: %w", err)
					}
					internalAsset.PublishRule.PublishAt = publishAt
				}
			case "/unpublishAt":
				if patch.Value == nil || *patch.Value == "" {
					internalAsset.PublishRule.UnpublishAt = time.Time{}
				} else {
					unpublishAt, err := time.Parse(time.RFC3339, *patch.Value)
					if err != nil {
						return nil, fmt.Errorf("invalid unpublishAt format: %w", err)
					}
					internalAsset.PublishRule.UnpublishAt = unpublishAt
				}
			case "/regions":
				if patch.Value == nil || *patch.Value == "" {
					internalAsset.PublishRule.Regions = nil
				} else {
					var regions []string
					if err := json.Unmarshal([]byte(*patch.Value), &regions); err != nil {
						return nil, fmt.Errorf("invalid regions format: %w", err)
					}
					internalAsset.PublishRule.Regions = regions
				}
			case "/ageRating":
				if patch.Value == nil || *patch.Value == "" {
					internalAsset.PublishRule.AgeRating = ""
				} else {
					internalAsset.PublishRule.AgeRating = *patch.Value
				}
			}
		case "remove":
			switch patch.Path {
			case "/publishAt":
				internalAsset.PublishRule.PublishAt = time.Time{}
			case "/unpublishAt":
				internalAsset.PublishRule.UnpublishAt = time.Time{}
			case "/regions":
				internalAsset.PublishRule.Regions = nil
			case "/ageRating":
				internalAsset.PublishRule.AgeRating = ""
			}
		}
	}

	err = r.Resolver.AssetService.UpdateAsset(ctx, id, internalAsset)
	if err != nil {
		return nil, fmt.Errorf("failed to patch publish rule: %w", err)
	}

	updatedAsset, err := r.Resolver.AssetService.GetAssetByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get updated asset: %w", err)
	}

	return mapAssetToGraphQL(updatedAsset), nil
}

// AddVideo is the resolver for the addVideo field.
func (r *mutationResolver) AddVideo(ctx context.Context, assetID string, typeArg model.VideoType, format string, bucket string, key string, url string, contentType string, size int) (*model.Asset, error) {
	var assetVideoType asset.VideoType
	switch typeArg {
	case model.VideoTypeMain:
		assetVideoType = asset.VideoTypeMain
	case model.VideoTypeTrailer:
		assetVideoType = asset.VideoTypeTrailer
	case model.VideoTypeBehindTheScenes:
		assetVideoType = asset.VideoTypeBehind
	case model.VideoTypeInterview:
		assetVideoType = asset.VideoTypeInterview
	}

	s3Object := asset.S3Object{
		Bucket: bucket,
		Key:    key,
		URL:    url,
	}

	video := &asset.Video{
		Type:            assetVideoType,
		Format:          asset.VideoFormat(format),
		StorageLocation: s3Object,
		ContentType:     contentType,
		Size:            int64(size),
		Status:          "pending",
	}

	err := r.Resolver.AssetService.AddVideo(ctx, assetID, video)
	if err != nil {
		return nil, fmt.Errorf("failed to add video: %w", err)
	}

	updatedAsset, err := r.Resolver.AssetService.GetAssetByID(ctx, assetID)
	if err != nil {
		return nil, fmt.Errorf("failed to get updated asset: %w", err)
	}

	return mapAssetToGraphQL(updatedAsset), nil
}

// DeleteVideo is the resolver for the deleteVideo field.
func (r *mutationResolver) DeleteVideo(ctx context.Context, assetID string, videoID string) (*model.Asset, error) {
	assetObj, err := r.Resolver.AssetService.GetAssetByID(ctx, assetID)
	if err != nil {
		return nil, fmt.Errorf("failed to get asset: %w", err)
	}

	var filesToDelete []struct {
		Bucket string `json:"bucket"`
		Key    string `json:"key"`
	}
	for _, video := range assetObj.Videos {
		if video.ID == videoID {
			filesToDelete = append(filesToDelete, struct {
				Bucket string `json:"bucket"`
				Key    string `json:"key"`
			}{
				Bucket: video.StorageLocation.Bucket,
				Key:    video.StorageLocation.Key,
			})
			if video.Thumbnail != nil && video.Thumbnail.StorageLocation != nil {
				filesToDelete = append(filesToDelete, struct {
					Bucket string `json:"bucket"`
					Key    string `json:"key"`
				}{
					Bucket: video.Thumbnail.StorageLocation.Bucket,
					Key:    video.Thumbnail.StorageLocation.Key,
				})
			}
			break
		}
	}

	err = r.Resolver.AssetService.DeleteVideo(ctx, assetID, videoID)
	if err != nil {
		return nil, fmt.Errorf("failed to delete video: %w", err)
	}

	if len(filesToDelete) > 0 {
		go func() {
			bgCtx := context.Background()
			_ = r.deleteAssetFiles(bgCtx, assetID, filesToDelete)
		}()
	}

	updatedAsset, err := r.Resolver.AssetService.GetAssetByID(ctx, assetID)
	if err != nil {
		return nil, fmt.Errorf("failed to get updated asset: %w", err)
	}

	return mapAssetToGraphQL(updatedAsset), nil
}

// AddImage is the resolver for the addImage field.
func (r *mutationResolver) AddImage(ctx context.Context, assetID string, typeArg model.ImageType, fileName string, bucket string, key string, url string, contentType string, size int) (*model.Asset, error) {
	var imageType asset.ImageType
	switch typeArg {
	case model.ImageTypeThumbnail:
		imageType = asset.ImageTypeThumbnail
	case model.ImageTypePoster:
		imageType = asset.ImageTypePoster
	case model.ImageTypeBanner:
		imageType = asset.ImageTypeBanner
	case model.ImageTypeHero:
		imageType = asset.ImageTypeHero
	case model.ImageTypeLogo:
		imageType = asset.ImageTypeLogo
	case model.ImageTypeScreenshot:
		imageType = asset.ImageTypeScreenshot

	default:
		return nil, fmt.Errorf("unknown image type: %s", typeArg)
	}

	internalImage := &asset.Image{
		FileName: fileName,
		URL:      url,
		Type:     imageType,
		StorageLocation: &asset.S3Object{
			Bucket: bucket,
			Key:    key,
			URL:    url,
		},
		Size:        int64(size),
		ContentType: contentType,
	}

	err := r.Resolver.AssetService.AddImage(ctx, assetID, internalImage)
	if err != nil {
		return nil, fmt.Errorf("failed to add image: %w", err)
	}

	updatedAsset, err := r.Resolver.AssetService.GetAssetByID(ctx, assetID)
	if err != nil {
		return nil, fmt.Errorf("failed to get updated asset: %w", err)
	}

	return mapAssetToGraphQL(updatedAsset), nil
}

// DeleteImage is the resolver for the deleteImage field.
func (r *mutationResolver) DeleteImage(ctx context.Context, assetID string, imageID string) (*model.Asset, error) {
	err := r.Resolver.AssetService.DeleteImage(ctx, assetID, imageID)
	if err != nil {
		return nil, fmt.Errorf("failed to delete image: %w", err)
	}

	updatedAsset, err := r.Resolver.AssetService.GetAssetByID(ctx, assetID)
	if err != nil {
		return nil, fmt.Errorf("failed to get updated asset: %w", err)
	}

	return mapAssetToGraphQL(updatedAsset), nil
}

// CreateBucket is the resolver for the createBucket field.
func (r *mutationResolver) CreateBucket(ctx context.Context, input model.BucketInput) (*model.Bucket, error) {
	internalBucket := mapGraphQLBucketInputToBucket(input)

	createdBucket, err := r.Resolver.BucketService.CreateBucket(ctx, internalBucket)
	if err != nil {
		return nil, fmt.Errorf("failed to create bucket: %w", err)
	}

	return mapBucketToGraphQL(createdBucket), nil
}

// UpdateBucket is the resolver for the updateBucket field.
func (r *mutationResolver) UpdateBucket(ctx context.Context, id string, input model.UpdateBucketInput) (*model.Bucket, error) {
	internalBucket := mapGraphQLUpdateBucketInputToBucket(input)

	err := r.Resolver.BucketService.UpdateBucket(ctx, id, internalBucket)
	if err != nil {
		return nil, fmt.Errorf("failed to update bucket: %w", err)
	}

	updatedBucket, err := r.Resolver.BucketService.GetBucketByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get updated bucket: %w", err)
	}

	return mapBucketToGraphQL(updatedBucket), nil
}

// PatchBucket is the resolver for the patchBucket field.
func (r *mutationResolver) PatchBucket(ctx context.Context, id string, patches []*model.JSONPatch) (*model.Bucket, error) {
	patchMap := make(map[string]interface{})

	for _, patch := range patches {
		if patch.Path == "/id" || patch.Path == "/key" {
			return nil, fmt.Errorf("cannot modify id or key fields")
		}

		switch patch.Path {
		case "/name":
			patchMap["name"] = patch.Value
		case "/description":
			patchMap["description"] = patch.Value
		case "/type":
			patchMap["type"] = patch.Value
		case "/status":
			patchMap["status"] = patch.Value
		default:
			return nil, fmt.Errorf("unsupported patch path: %s", patch.Path)
		}
	}

	err := r.Resolver.BucketService.PatchBucket(ctx, id, patchMap)
	if err != nil {
		return nil, fmt.Errorf("failed to patch bucket: %w", err)
	}

	patchedBucket, err := r.Resolver.BucketService.GetBucketByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get patched bucket: %w", err)
	}

	return mapBucketToGraphQL(patchedBucket), nil
}

// DeleteBucket is the resolver for the deleteBucket field.
func (r *mutationResolver) DeleteBucket(ctx context.Context, id string) (bool, error) {
	err := r.Resolver.BucketService.DeleteBucket(ctx, id)
	if err != nil {
		return false, fmt.Errorf("failed to delete bucket: %w", err)
	}
	return true, nil
}

// AddAssetToBucket is the resolver for the addAssetToBucket field.
func (r *mutationResolver) AddAssetToBucket(ctx context.Context, bucketID string, assetID string) (*model.Bucket, error) {
	err := r.Resolver.BucketService.AddAssetToBucket(ctx, bucketID, assetID)
	if err != nil {
		return nil, fmt.Errorf("failed to add asset to bucket: %w", err)
	}

	updatedBucket, err := r.Resolver.BucketService.GetBucketByID(ctx, bucketID)
	if err != nil {
		return nil, fmt.Errorf("failed to get updated bucket: %w", err)
	}

	return mapBucketToGraphQL(updatedBucket), nil
}

// RemoveAssetFromBucket is the resolver for the removeAssetFromBucket field.
func (r *mutationResolver) RemoveAssetFromBucket(ctx context.Context, bucketID string, assetID string) (*model.Bucket, error) {
	err := r.Resolver.BucketService.RemoveAssetFromBucket(ctx, bucketID, assetID)
	if err != nil {
		return nil, fmt.Errorf("failed to remove asset from bucket: %w", err)
	}

	updatedBucket, err := r.Resolver.BucketService.GetBucketByID(ctx, bucketID)
	if err != nil {
		return nil, fmt.Errorf("failed to get updated bucket: %w", err)
	}

	return mapBucketToGraphQL(updatedBucket), nil
}

// Asset is the resolver for the asset field.
func (r *queryResolver) Asset(ctx context.Context, id string) (*model.Asset, error) {
	internalAsset, err := r.Resolver.AssetService.GetAssetByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get asset: %w", err)
	}

	return mapAssetToGraphQL(internalAsset), nil
}

// AssetBySlug is the resolver for the assetBySlug field.
func (r *queryResolver) AssetBySlug(ctx context.Context, slug string) (*model.Asset, error) {
	internalAsset, err := r.Resolver.AssetService.GetAssetBySlug(ctx, slug)
	if err != nil {
		return nil, fmt.Errorf("failed to get asset by slug: %w", err)
	}

	return mapAssetToGraphQL(internalAsset), nil
}

// Assets is the resolver for the assets field.
func (r *queryResolver) Assets(ctx context.Context, limit *int, nextKey *string) (*model.AssetPage, error) {
	limitValue := 10
	if limit != nil {
		limitValue = *limit
	}

	var lastKey map[string]interface{}
	if nextKey != nil {
		lastKey = map[string]interface{}{"nextKey": *nextKey}
	}

	assetPage, err := r.Resolver.AssetService.ListAssets(ctx, limitValue, lastKey)
	if err != nil {
		return nil, fmt.Errorf("failed to list assets: %w", err)
	}

	return mapAssetPageToGraphQL(assetPage), nil
}

// AssetsByParent is the resolver for the assetsByParent field.
func (r *queryResolver) AssetsByParent(ctx context.Context, parentID string, limit *int, nextKey *string) (*model.AssetPage, error) {
	children, err := r.Resolver.AssetService.GetChildren(ctx, parentID)
	if err != nil {
		return nil, fmt.Errorf("failed to get children: %w", err)
	}

	var result []*model.Asset
	for _, child := range children {
		result = append(result, mapAssetToGraphQL(&child))
	}

	return &model.AssetPage{
		Items: result,
	}, nil
}

// SearchAssets is the resolver for the searchAssets field.
func (r *queryResolver) SearchAssets(ctx context.Context, query string, limit *int, nextKey *string) (*model.AssetPage, error) {
	limitValue := 10
	if limit != nil {
		limitValue = *limit
	}

	var lastKey map[string]interface{}
	if nextKey != nil {
		lastKey = map[string]interface{}{"nextKey": *nextKey}
	}

	assetPage, err := r.Resolver.AssetService.SearchAssets(ctx, query, limitValue, lastKey)
	if err != nil {
		return nil, fmt.Errorf("failed to search assets: %w", err)
	}

	return mapAssetPageToGraphQL(assetPage), nil
}

// Bucket is the resolver for the bucket field.
func (r *queryResolver) Bucket(ctx context.Context, id string) (*model.Bucket, error) {
	log := logger.Get().WithService("graphql-resolver")

	bucket, err := r.Resolver.BucketService.GetBucketByID(ctx, id)
	if err != nil {
		log.WithError(err).Error("Failed to get bucket by ID from service", "bucket_id", id)
		return nil, fmt.Errorf("failed to get bucket: %w", err)
	}

	return mapBucketToGraphQL(bucket), nil
}

// BucketByKey is the resolver for the bucketByKey field.
func (r *queryResolver) BucketByKey(ctx context.Context, key string) (*model.Bucket, error) {
	log := logger.Get().WithService("graphql-resolver")

	bucket, err := r.Resolver.BucketService.GetBucketByKey(ctx, key)
	if err != nil {
		log.WithError(err).Error("Failed to get bucket by key from service", "key", key)
		return nil, fmt.Errorf("failed to get bucket by key: %w", err)
	}

	return mapBucketToGraphQL(bucket), nil
}

// Buckets is the resolver for the buckets field.
func (r *queryResolver) Buckets(ctx context.Context, limit *int, nextKey *string) (*model.BucketPage, error) {
	limitValue := 10
	if limit != nil {
		limitValue = *limit
	}

	bucketPage, err := r.Resolver.BucketService.ListBuckets(ctx, limitValue)
	if err != nil {
		return nil, fmt.Errorf("failed to list buckets: %w", err)
	}

	return mapBucketPageToGraphQL(bucketPage), nil
}

// Bucket returns BucketResolver implementation.
func (r *Resolver) Bucket() BucketResolver { return &bucketResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type bucketResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
