// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Asset struct {
	ID          string       `json:"id"`
	Slug        string       `json:"slug"`
	Title       *string      `json:"title,omitempty"`
	Description *string      `json:"description,omitempty"`
	Type        AssetType    `json:"type"`
	Genre       *string      `json:"genre,omitempty"`
	Genres      []string     `json:"genres,omitempty"`
	Tags        []string     `json:"tags,omitempty"`
	Status      *string      `json:"status,omitempty"`
	CreatedAt   time.Time    `json:"createdAt"`
	UpdatedAt   time.Time    `json:"updatedAt"`
	Metadata    *string      `json:"metadata,omitempty"`
	OwnerID     *string      `json:"ownerId,omitempty"`
	Videos      []*Video     `json:"videos,omitempty"`
	PublishRule *PublishRule `json:"publishRule,omitempty"`
	Parent      *Asset       `json:"parent,omitempty"`
	Children    []*Asset     `json:"children,omitempty"`
	Buckets     []*Bucket    `json:"buckets,omitempty"`
}

type AssetInput struct {
	Slug        string    `json:"slug"`
	Title       *string   `json:"title,omitempty"`
	Description *string   `json:"description,omitempty"`
	Type        AssetType `json:"type"`
	Genre       *string   `json:"genre,omitempty"`
	Genres      []string  `json:"genres,omitempty"`
	Tags        []string  `json:"tags,omitempty"`
	Metadata    *string   `json:"metadata,omitempty"`
	OwnerID     *string   `json:"ownerId,omitempty"`
	ParentID    *string   `json:"parentId,omitempty"`
}

type AssetPage struct {
	Items   []*Asset `json:"items"`
	NextKey *string  `json:"nextKey,omitempty"`
}

type Bucket struct {
	ID          string        `json:"id"`
	Key         string        `json:"key"`
	Name        string        `json:"name"`
	Description *string       `json:"description,omitempty"`
	Type        BucketType    `json:"type"`
	Status      *BucketStatus `json:"status,omitempty"`
	AssetIds    []string      `json:"assetIds,omitempty"`
	CreatedAt   time.Time     `json:"createdAt"`
	UpdatedAt   time.Time     `json:"updatedAt"`
	Assets      []*Asset      `json:"assets,omitempty"`
}

type BucketInput struct {
	Key         string        `json:"key"`
	Name        string        `json:"name"`
	Description *string       `json:"description,omitempty"`
	Type        BucketType    `json:"type"`
	Status      *BucketStatus `json:"status,omitempty"`
	AssetIds    []string      `json:"assetIds,omitempty"`
}

type BucketPage struct {
	Items   []*Bucket `json:"items"`
	NextKey *string   `json:"nextKey,omitempty"`
}

type Image struct {
	FileName        string    `json:"fileName"`
	URL             string    `json:"url"`
	StorageLocation *S3Object `json:"storageLocation,omitempty"`
	Width           *int      `json:"width,omitempty"`
	Height          *int      `json:"height,omitempty"`
	Size            *int      `json:"size,omitempty"`
	ContentType     *string   `json:"contentType,omitempty"`
	Metadata        *string   `json:"metadata,omitempty"`
}

type JSONPatch struct {
	Op    string  `json:"op"`
	Path  string  `json:"path"`
	Value *string `json:"value,omitempty"`
}

type Mutation struct {
}

type PublishRule struct {
	IsPublic    bool       `json:"isPublic"`
	PublishAt   *time.Time `json:"publishAt,omitempty"`
	UnpublishAt *time.Time `json:"unpublishAt,omitempty"`
	Regions     []string   `json:"regions,omitempty"`
	AgeRating   *string    `json:"ageRating,omitempty"`
}

type Query struct {
}

type S3Object struct {
	Bucket string `json:"bucket"`
	Key    string `json:"key"`
	URL    string `json:"url"`
}

type StreamInfo struct {
	DownloadURL *string `json:"downloadUrl,omitempty"`
	CdnPrefix   *string `json:"cdnPrefix,omitempty"`
}

type UpdateBucketInput struct {
	Name        string        `json:"name"`
	Description *string       `json:"description,omitempty"`
	Type        BucketType    `json:"type"`
	Status      *BucketStatus `json:"status,omitempty"`
}

type Video struct {
	Type      VideoType    `json:"type"`
	Raw       *VideoFormat `json:"raw,omitempty"`
	Hls       *VideoFormat `json:"hls,omitempty"`
	Dash      *VideoFormat `json:"dash,omitempty"`
	Thumbnail *Image       `json:"thumbnail,omitempty"`
	Status    *string      `json:"status,omitempty"`
}

type VideoFormat struct {
	StorageLocation *S3Object   `json:"storageLocation"`
	Width           *int        `json:"width,omitempty"`
	Height          *int        `json:"height,omitempty"`
	Duration        *float64    `json:"duration,omitempty"`
	Bitrate         *int        `json:"bitrate,omitempty"`
	Codec           *string     `json:"codec,omitempty"`
	Size            *int        `json:"size,omitempty"`
	ContentType     *string     `json:"contentType,omitempty"`
	StreamInfo      *StreamInfo `json:"streamInfo,omitempty"`
	Metadata        *string     `json:"metadata,omitempty"`
}

type AssetType string

const (
	AssetTypeMovie           AssetType = "MOVIE"
	AssetTypeSeries          AssetType = "SERIES"
	AssetTypeSeason          AssetType = "SEASON"
	AssetTypeEpisode         AssetType = "EPISODE"
	AssetTypeDocumentary     AssetType = "DOCUMENTARY"
	AssetTypeMusic           AssetType = "MUSIC"
	AssetTypePodcast         AssetType = "PODCAST"
	AssetTypeTrailer         AssetType = "TRAILER"
	AssetTypeBehindTheScenes AssetType = "BEHIND_THE_SCENES"
	AssetTypeInterview       AssetType = "INTERVIEW"
)

var AllAssetType = []AssetType{
	AssetTypeMovie,
	AssetTypeSeries,
	AssetTypeSeason,
	AssetTypeEpisode,
	AssetTypeDocumentary,
	AssetTypeMusic,
	AssetTypePodcast,
	AssetTypeTrailer,
	AssetTypeBehindTheScenes,
	AssetTypeInterview,
}

func (e AssetType) IsValid() bool {
	switch e {
	case AssetTypeMovie, AssetTypeSeries, AssetTypeSeason, AssetTypeEpisode, AssetTypeDocumentary, AssetTypeMusic, AssetTypePodcast, AssetTypeTrailer, AssetTypeBehindTheScenes, AssetTypeInterview:
		return true
	}
	return false
}

func (e AssetType) String() string {
	return string(e)
}

func (e *AssetType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AssetType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AssetType", str)
	}
	return nil
}

func (e AssetType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AssetType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AssetType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BucketStatus string

const (
	BucketStatusActive   BucketStatus = "ACTIVE"
	BucketStatusInactive BucketStatus = "INACTIVE"
	BucketStatusDraft    BucketStatus = "DRAFT"
)

var AllBucketStatus = []BucketStatus{
	BucketStatusActive,
	BucketStatusInactive,
	BucketStatusDraft,
}

func (e BucketStatus) IsValid() bool {
	switch e {
	case BucketStatusActive, BucketStatusInactive, BucketStatusDraft:
		return true
	}
	return false
}

func (e BucketStatus) String() string {
	return string(e)
}

func (e *BucketStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BucketStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BucketStatus", str)
	}
	return nil
}

func (e BucketStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BucketStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BucketStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BucketType string

const (
	BucketTypeCollection BucketType = "COLLECTION"
	BucketTypePlaylist   BucketType = "PLAYLIST"
	BucketTypeCategory   BucketType = "CATEGORY"
)

var AllBucketType = []BucketType{
	BucketTypeCollection,
	BucketTypePlaylist,
	BucketTypeCategory,
}

func (e BucketType) IsValid() bool {
	switch e {
	case BucketTypeCollection, BucketTypePlaylist, BucketTypeCategory:
		return true
	}
	return false
}

func (e BucketType) String() string {
	return string(e)
}

func (e *BucketType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BucketType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BucketType", str)
	}
	return nil
}

func (e BucketType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BucketType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BucketType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type VideoType string

const (
	VideoTypeMain            VideoType = "MAIN"
	VideoTypeTrailer         VideoType = "TRAILER"
	VideoTypeBehindTheScenes VideoType = "BEHIND_THE_SCENES"
	VideoTypeInterview       VideoType = "INTERVIEW"
)

var AllVideoType = []VideoType{
	VideoTypeMain,
	VideoTypeTrailer,
	VideoTypeBehindTheScenes,
	VideoTypeInterview,
}

func (e VideoType) IsValid() bool {
	switch e {
	case VideoTypeMain, VideoTypeTrailer, VideoTypeBehindTheScenes, VideoTypeInterview:
		return true
	}
	return false
}

func (e VideoType) String() string {
	return string(e)
}

func (e *VideoType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = VideoType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid VideoType", str)
	}
	return nil
}

func (e VideoType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *VideoType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e VideoType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
